spring:
  profiles:
    group:
      local:
        - local
        - aws
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 클라이언트 아이디
            client-secret: 비밀키
            scope: profile, email

kakao:
  client:
    id: 클라이언트 아이디
    secret: 비밀키

oauth2:
  success:
    redirect:
      url: http://localhost:3000/callback/

logging.level:
  org.hibernate.SQL: debug
---

spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/rubminds?serverTimezone=Asia/Seoul&charset=UTF-8'
    username: root
    password: pass

tmp:
  file:
    prefix:

jwt:
  access-token-props:
    secret: 'c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK'
    expiration-time-milli-sec: 3600000
  refresh-token-props:
    secret: 'ZlLHyRf4Ru3CnpVVl6hk9InHkAcHG07x82PufcFR4S4pKnLn0WJgtu4VQERoJauKi2hNIgWCuQF9aFQM7VJGlw=='
    expiration-time-milli-sec: 864000000

