GET {{apiUrl}}/message/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/message/
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "postId" : 1,
  "receiverId" : 3,
  "content" : "내용"

}
