###
GET {{apiUrl}}/chat/1?page=2&size=5
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
GET {{apiUrl}}/chat?page=1&size=5&kinds=PROJECT
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8


###
POST {{apiUrl}}/chat
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "postId" : 1,
  "content" : "3번입니다."

}
