###
GET {{apiUrl}}/chat/1?page=1&size=5
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
GET {{apiUrl}}/chat?page=1&size=5
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8


###
POST {{apiUrl}}/chat
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "postId" : 4,
  "content" : "1번입니다."

}
