GET {{apiUrl}}/post/2
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8


###
POST {{apiUrl}}/post
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json, image/*

--boundary
Content-Disposition: form-data; name="postInfo";
Content-Type: application/json;charset=UTF-8

{
  "title": "테스트",
  "content": "테스트내용",
  "headcount": 3,
  "kinds": "PROJECT",
  "meeting": "ONLINE",
  "region": "서울",
  "skillIds": [
    2,
    3
  ],
  "customSkillName": [
    "firebase",
    "spring"
  ]
}
--boundary
Content-Disposition: form-data; name="files"; filename="white.jpeg"

< ./../main/resources/dummy/image/white.jpeg


###
PUT {{apiUrl}}/post/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "title": "123",
  "content": "수정완료",
  "headcount": 1,
  "kinds": "PROJECT",
  "meeting": "BOTH",
  "postsStatus": "GATHERING",
  "region": "서울",
  "skillIds": [
    1,
    2
  ],
  "customSkillName": [
    "firebase",
    "mysql"
  ]
}

###
DELETE {{apiUrl}}/post/6
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
GET {{apiUrl}}/post/getPosts
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
GET {{apiUrl}}/post/getLikePosts
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/postLike
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "postId": 1
}