GET {{apiUrl}}/post/3
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8


###
POST {{apiUrl}}/post
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "title": "2요",
  "content": "스터디 모집합니다",
  "headcount": 3,
  "kinds": "PROJECT",
  "meeting": "ONLINE",
  "region": "서울",
  "skillIds": [
    2,
    3
  ],
  "customSkillName": [
    "firebase",
    "spring"
  ]
}

###
PUT {{apiUrl}}/post/11
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "title": "123",
  "content": "수정완료",
  "headcount": 1,
  "kinds": "PROJECT",
  "meeting": "BOTH",
  "postsStatus": "GATHERING",
  "region": "서울",
  "skillIds": [
    1,
    2
  ],
  "customSkillName": [
    "firebase",
    "mysql"
  ]
}

###
DELETE {{apiUrl}}/post/6
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

