POST {{apiUrl}}/user/signup
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar";


--boundary
Content-Disposition: form-data; name="nickname";

테스트1
--boundary
Content-Disposition: form-data; name="job";

학생
--boundary
Content-Disposition: form-data; name="introduce";

test
--boundary
Content-Disposition: form-data; name="skillIds";

2,6
--boundary
Content-Disposition: form-data; name="isChanged";

false

###
POST {{apiUrl}}/user/update
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="white.jpeg"

< ./../main/resources/dummy/image/white.jpeg
--boundary
Content-Disposition: form-data; name="nickname";

테스트
--boundary
Content-Disposition: form-data; name="job";

학생
--boundary
Content-Disposition: form-data; name="introduce";

test
--boundary
Content-Disposition: form-data; name="skillIds";

1,3
--boundary
Content-Disposition: form-data; name="isChanged";

true
###
GET {{apiUrl}}/user/me
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
GET {{apiUrl}}/user/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

